# Generated by Django 6.0.3 on 2026-04-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_passwordreset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordReset",
        ),
    ]
