# Generated by Django 6.0.3 on 2026-03-21 23:26

import apps.companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Essai"),
                            ("active", "Actif"),
                            ("expired", "Expiré"),
                            ("suspended", "Suspendu"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Statut abonnement",
                    ),
                ),
                (
                    "monthly_quota",
                    models.IntegerField(default=500, verbose_name="Quota mensuel"),
                ),
                (
                    "contacts_used_this_month",
                    models.IntegerField(
                        default=0, verbose_name="Contacts utilisés ce mois"
                    ),
                ),
                (
                    "quota_reset_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prochain renouvellement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "current_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="billing.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.companies.models.company_upload_path,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Nom original"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "Traitement en cours"),
                            ("cleaning", "Nettoyage téléphonique"),
                            ("filtering", "Application des filtres"),
                            ("ready", "Prêt pour export"),
                            ("failed", "Échec"),
                            ("expired", "Expiré"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="Progression %"),
                ),
                (
                    "columns_detected",
                    models.JSONField(default=list, verbose_name="Colonnes détectées"),
                ),
                (
                    "column_mapping",
                    models.JSONField(default=dict, verbose_name="Mapping colonnes"),
                ),
                (
                    "filters_config",
                    models.JSONField(default=dict, verbose_name="Config filtres"),
                ),
                (
                    "scoring_config",
                    models.JSONField(default=dict, verbose_name="Config scoring"),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.companies.models.company_result_path,
                        verbose_name="Fichier résultat",
                    ),
                ),
                (
                    "rows_original",
                    models.IntegerField(default=0, verbose_name="Lignes originales"),
                ),
                (
                    "rows_after_filter",
                    models.IntegerField(default=0, verbose_name="Lignes après filtre"),
                ),
                (
                    "rows_valid_phones",
                    models.IntegerField(default=0, verbose_name="Numéros valides"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier uploadé",
                "verbose_name_plural": "Fichiers uploadés",
            },
        ),
        migrations.CreateModel(
            name="ProcessingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Fichier original"),
                ),
                (
                    "rows_original",
                    models.IntegerField(default=0, verbose_name="Lignes originales"),
                ),
                (
                    "rows_after_filter",
                    models.IntegerField(default=0, verbose_name="Lignes après filtre"),
                ),
                (
                    "rows_valid_phones",
                    models.IntegerField(default=0, verbose_name="Numéros valides"),
                ),
                (
                    "filters_applied",
                    models.JSONField(default=dict, verbose_name="Filtres appliqués"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "export_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.companies.models.company_export_path,
                        verbose_name="Fichier export",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Format export",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processings",
                        to="companies.company",
                    ),
                ),
                (
                    "upload",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_history",
                        to="companies.uploadedfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique traitement",
                "verbose_name_plural": "Historiques traitements",
            },
        ),
    ]
