# Generated by Django 6.0.3 on 2026-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Attente"),
                    ("processing", "Traitement"),
                    ("cleaning", "Nettoyage"),
                    ("filtering", "Application"),
                    ("ready", "Prêt"),
                    ("failed", "Échec"),
                    ("expired", "Expiré"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
