# Generated by Django 6.0.3 on 2026-03-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix mensuel (€)",
                    ),
                ),
                (
                    "monthly_quota",
                    models.IntegerField(
                        default=500, verbose_name="Quota mensuel (contacts)"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Fonctionnalités"
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Stripe Price ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
            },
        ),
    ]
